import { createElement } from '@lwc/engine-dom';
import Wsm_shipment_csv_output from 'c/wsm_shipment_csv_output';

describe('c-wsm-shipment-csv-output', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-wsm-shipment-csv-output', {
            is: Wsm_shipment_csv_output
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});